/* CONCEPTOS DDL(DATA DEFINITION LANGUAGE) MEJOR APLICADOS HASTA EL MOMENTO, SIRVE DE REFERENCIA PARA LA CREACIÓN DE NUEVAS BASES DE DATOS */
CREATE DATABASE adminProHospitals;

USE adminProhospitales;

CREATE TABLE
IF NOT EXISTS hospitals
(
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name TEXT NOT NULL,
  img TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE
IF NOT EXISTS doctors
(
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR
(20) NOT NULL,
  img TEXT NULL,
  hospital_id INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_hospitals_doctors FOREIGN KEY
(hospital_id) REFERENCES hospitals
(id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE
IF NOT EXISTS users
(
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR
(20) NOT NULL,
  password VARCHAR
(70) NOT NULL,
  email VARCHAR
(25) NOT NULL UNIQUE,
  img TEXT NULL,
  role VARCHAR
(25) NOT NULL DEFAULT 'USER_ROLE',
  google BOOLEAN NULL,
  doctor_id INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_doctors_users FOREIGN KEY
(doctor_id) REFERENCES doctors
(id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

/* Agregando Un Campo A La Tabla De Users */
ALTER TABLE users ADD activate BOOLEAN NOT NULL DEFAULT true;

/* Modificando Un Campo De La Tabla Users */
ALTER TABLE users MODIFY google BOOLEAN NULL DEFAULT FALSE;
ALTER TABLE users MODIFY doctor_id INT NOT NULL DEFAULT 0;
/* No Es Válido */
ALTER TABLE users MODIFY doctor_id INT NULL;